apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-production
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm/techtrends
    repoURL: https://github.com/badrmoh/nd064_course_1 
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc