name: TechTrends - Package with Docker
on:
  push:
    branches: [ main ]
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Only build when it is a pull request
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
            
      - name: Build and push techtrends app docker image
        uses: docker/build-push-action@v2
        with:
          context: project
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/techtrends:latest
          push: ${{ github.event_name != 'pull_request' }}